---
title: "Luis Rivera"
format: html
css: styles.css
toc: false
---
  
303-960-6369 | LuisRaulRivera24@gmail.com | [linkedin.com/in/luisrivera98](https://linkedin.com/in/luisrivera98)  

::: {.header-box}
## Areas of Expertise
:::

<ul class="expertise-list">
  <li>Algorithm Tools</li>
  <li>Design Metrics</li>
  <li>Object-oriented Programming</li>
  <li>Data Spreadsheet Summary</li>
  <li>Probability Distributions</li>
  <li>Hypothesis Testing</li>
  <li>R Programming</li>
  <li>Statistical Testing</li>
  <li>Data Analysis/Evaluation</li>
  <li>Research Techniques</li>
  <li>Research Design</li>
  <li>Process Planning</li>
  <li>Quality Management</li>
  <li>Forecasting Tools</li>
  <li>Policy Analysis</li>
  <li>SQL Commands With Joins</li>
  <li>Database Design</li>
  <li>Data Merging</li>
  <li>HTML Proficiency</li>
  <li>CSS Styling Proficiency</li>
</ul>

::: {.header-box}
## Education
:::

::: {style="text-decoration: underline; text-decoration-thickness: 0.05em; text-underline-offset: 0.25em"}
### MS in Business Analytics and Artificial Intelligence
:::
**University of Texas - Dallas** | Dallas, TX  
**Jan 2026 - Dec 2027** 

<ul class="education-list">
  <li>Data Science emphasis</li>
  <li>Coursework includes: Database Foundations, Advanced Statistics, Data Warehousing, Predictive Analytics, Business Analytics With R, Applied Machine Learning, Big Data, Applied Natural Language Processing, Applied Deep Learning, and AWS Cloud Solution Architecture.</li>
</ul>

---

::: {style="text-decoration: underline; text-decoration-thickness: 0.05em; text-underline-offset: 0.25em"}
### Data Science Online Coursework
:::
**Brigham Young University - Idaho** | Rexburg, ID  
**Aug 2024 - Dec 2025**  

<ul class="education-list">
  <li>GPA: 4.0</li>
  <li>Additional programming and data science courses taken through the BYU-I BS in Data Science major.</li>
  <li>Coursework included: Programming Building Blocks, Programming with Functions, Technical Teamwork, Algorithm Design, Web Fundamentals, Programming with Classes, Intro to Databases, SQL, and Data Science Programming.</li>
</ul>

---

::: {style="text-decoration: underline; text-decoration-thickness: 0.05em; text-underline-offset: 0.25em"}
### Bachelor of Arts in Public Policy and Administration
:::
**Brigham Young University - Idaho** | Rexburg, ID  
**Sep 2018 - Dec 2021** 

<ul class="education-list">
  <li>GPA: 3.9</li>
  <li>Emphasis in Public Administration</li>
  <li>Academic Scholarship - Thomas E. Ricks Grant</li>
</ul>

---

::: {.header-box}
## Professional Experience
:::

::: {style="text-decoration: underline; text-decoration-thickness: 0.05em; text-underline-offset: 0.25em"}
### Administrative Analyst I
:::  
**New Jersey Department of Transportation** | Transportation Mobility Research Unit  
**Jan 2023 - May 2024**

<ul class="education-professional-list">
  <li>Developed internal protocols for managing $3.5 million in annual federal funds related to the<br>
    Intelligent Transportation Resource Center.</li>
  <li>Managed federal contracts using the Financial Management Information System.</li>
  <li>Conducted research on Intelligent Transportation Systems to improve traffic flow and safety.</li>
  <li>Provided support in developing annual in-house budget for the Transportation Mobility Research Unit.</li>
  <li>Participated in State Transportation Innovation Council quarterly meetings.</li>
</ul>

---

::: {style="text-decoration: underline; text-decoration-thickness: 0.05em; text-underline-offset: 0.25em"}
### Instructor Evaluation Support Specialist/Statistics Tutoring Assistant
:::    
**Brigham Young University-Idaho** | Tutoring Center   
**Apr 2021 - Dec 2021**  

<ul class="education-professional-list">
  <li>Assigned grades for student coursework.</li>
  <li>Conducted exam review sessions and tutoring for a class of 50 students.</li>
  <li>Monitored BYU-I online instructor presence for 24 instructors daily.</li>
</ul>

---

::: {style="text-decoration: underline; text-decoration-thickness: 0.05em; text-underline-offset: 0.25em"}
### Custodian
::: 
**Brigham Young University-Idaho** | Custodial Unit  
**Jan 2019 - Apr 2020**  

<ul class="education-professional-list">
  <li>Performed routine cleaning and maintenance tasks across campus buildings.</li>
  <li>Managed waste disposal and maintained cleanliness in waste areas.</li>
  <li>Assisted with event setups and post-event cleanups.</li>
</ul>

---

::: {style="text-decoration: underline; text-decoration-thickness: 0.05em; text-underline-offset: 0.25em"}
### Ambassador
:::   
**Church of Jesus Christ of Latter-day Saints** | Full-Time Missionary  
**Aug 2016 - Jul 2018**  

<ul class="education-professional-list">
  <li>Oversaw the well-being of 30 full-time ambassadors.</li>
  <li>Provided community service and humanitarian aid.</li>
  <li>Shared the teachings of Jesus Christ and engaged in religious education.</li>
  <li>Trained ambassadors for missionary life and responsibilities.</li>
</ul>